wandb_project_name: imml
logdir: 'results/toy2/exp4'
logger: 
  type: base
  endwith: ['@', '#']
model:
  encoder:
    arch: fc_vec
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
  decoder:
    arch: fc_vec
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
  final_projection: True
  x_dim: 20
  z_dim: 5
  tau_dim: 2
data:
  training:
    dataset: Toy2
    root: datasets/EXP4
    batch_size: 10
    n_workers: 4
    split: training
    shuffle: True
    num_control_points: 10
  validation:
    dataset: Toy2
    root: datasets/EXP4
    batch_size: 10
    n_workers: 4
    split: validation
    shuffle: True
    num_control_points: 10
trainer: cAE
training:
  seed: 1
  n_epoch: 3000
  optimizer:
    name: 'adam'
    lr: 0.0001
  print_interval: 100
  val_interval: 100
  eval_interval: null
  visualize_interval: 1000