logdir: 'results/toy2/exp4/ae_zdim5_regnone_seed1/'
data:
  training:
    pretrained:
      identifier: ae_zdim5_regnone_seed1
      config_file: ae.yml
      ckpt_file: model_best.pkl
      root: results/toy2/exp4
  validation:
    pretrained:
      identifier: ae_zdim5_regnone_seed1
      config_file: ae.yml
      ckpt_file: model_best.pkl
      root: results/toy2/exp4