wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1698284547.413896
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.13.10
      8:
      - 3
      - 5
data:
  desc: null
  value:
    training:
      batch_size: 10
      dataset: Toy
      n_workers: 4
      num_control_points: 10
      root: datasets/EXP1
      shuffle: true
      split: training
    validation:
      batch_size: 10
      dataset: Toy
      n_workers: 4
      num_control_points: 10
      root: datasets/EXP1
      shuffle: true
      split: validation
device:
  desc: null
  value: cuda:0
logdir:
  desc: null
  value: results/toy/exp1
logger:
  desc: null
  value:
    endwith:
    - '@'
    - '#'
    type: base
model:
  desc: null
  value:
    T: 1
    arch: irae
    decoder:
      activation:
      - elu
      - elu
      - elu
      - elu
      arch: fc_vec
      l_hidden:
      - 256
      - 256
      - 256
      - 256
      out_activation: linear
    dim: 2
    encoder:
      activation:
      - elu
      - elu
      - elu
      - elu
      arch: fc_vec
      l_hidden:
      - 256
      - 256
      - 256
      - 256
      out_activation: linear
    init_final_projection: true
    iso_reg: 0.1
    metric: bezier
    num_control_points: 10
    x_dim: 20
    z_dim: 2
trainer:
  desc: null
  value: base
training:
  desc: null
  value:
    eval_interval: 100
    n_epoch: 3000
    optimizer:
      lr: 0.0001
      name: adam
    print_interval: 100
    val_interval: 100
    visualize_interval: 1000
wandb_project_name:
  desc: null
  value: imml
